monitoring_localconfig_path: "{{ playbook_dir }}/inventory/monitoring"
app_localconfig_path: "{{ playbook_dir }}/inventory/monitoring"
prometheus_service: prometheus
prometheus_version: 2.53.2
grafana_service: grafana-server
monitoring_loki_ipadress: 159.194.203.159
loki_version: 2.9.0
loki_service: loki.service
otl_collector_version: 0.151.0
tempo_version: 2.7.0