{
 "title": "Notebook",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "90 квантиль длительности запросов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{handler!~\"/metrics|/redoc|/openapi.json|/docs\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рост запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!~\"/metrics|/redoc|/openapi.json|/docs\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение запросов по эндпоинтам",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler, method) (http_requests_total{handler!~\"/metrics|/redoc|/openapi.json|/docs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение контактов по возрасту",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(business_contact_age_years_bucket) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}