[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
skip = [
    '.eggs', '.git', '.hg', '.mypy_cache', '.nox', '.pants.d', '.tox',
    '.venv', '_build', 'buck-out', 'build', 'dist', 'node_modules', 'venv',
]
skip_gitignore = true

[tool.pylint.main]
# Путь к исходникам
source-roots = ["src"]

# Игнорируемые файлы/папки
ignore = ["tests", "venv", ".venv", "__pycache__"]

# Расширения для проверки
extension-pkg-allow-list = ["pydantic", "typing_extensions"]

[tool.pylint.messages_control]
# Отключаем некоторые проверки для сгенерированного кода
disable = [
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
    "E0401",  # import-error
    "R0801",  # duplicate-code
    "R0903",  # too-few-public-methods
    "W0611",  # unused-import
]

[tool.pylint.format]
max-line-length = 100

[tool.mypy]
python_version = "3.11"
mypy_path = "src"
ignore_missing_imports = true

[tool.mypy.overrides]
module = [
    "openapi_server.apis.default_api_base",
    "openapi_server.apis.default_api",
    "openapi_server.models.*",
]
ignore_errors = true

[tool.mypy.metrics]
ignore_errors = true