# coding: utf-8
import logging
from logging.handlers import RotatingFileHandler

file_handler = RotatingFileHandler(
    '/var/log/myapp/app.log',  
    maxBytes=10_000_000,      
    backupCount=1
)

logging.basicConfig(
    handlers=[file_handler],
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

from fastapi import FastAPI
from prometheus_fastapi_instrumentator import Instrumentator
from openapi_server.apis.default_api import router as DefaultApiRouter

# Импортируем метрики из отдельного файла (чтобы они зарегистрировались)
from metrics import *

app = FastAPI(
    title="Notebook API",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.0.1",
)

Instrumentator().instrument(app).expose(app)

app.include_router(DefaultApiRouter)
