"""Главный модуль FastAPI приложения.

Настраивает:
- логирование
- OpenTelemetry для трейсинга
- Prometheus метрики
- маршруты API
"""

# coding: utf-8
import logging
from logging.handlers import RotatingFileHandler

from fastapi import FastAPI
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from prometheus_fastapi_instrumentator import Instrumentator

# Импортируем метрики (отключаем pylint для wildcard-импорта)
from metrics import *  # pylint: disable=wildcard-import,unused-wildcard-import
from openapi_server.apis.default_api import router as DefaultApiRouter

# Настройка логирования
file_handler = RotatingFileHandler(
    "/var/log/myapp/app.log", maxBytes=10_000_000, backupCount=1
)

logging.basicConfig(
    handlers=[file_handler],
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)

# Создание FastAPI приложения
app = FastAPI(
    title="Notebook API",
    description="No description provided (generated by Openapi Generator "
    "https://github.com/openapitools/openapi-generator)",
    version="0.0.1",
)

# Настройка Prometheus метрик
Instrumentator().instrument(app).expose(app)

# Настройка OpenTelemetry
resource = Resource.create({"service.name": "my-app", "service.version": "1.0.0"})

provider = TracerProvider(resource=resource)

OTLP_ENDPOINT = "localhost:4343"
otlp_exporter = OTLPSpanExporter(endpoint=OTLP_ENDPOINT, insecure=True)

provider.add_span_processor(BatchSpanProcessor(otlp_exporter))

trace.set_tracer_provider(provider)

# Инструментируем FastAPI
FastAPIInstrumentor.instrument_app(app)

# Подключаем роутеры
app.include_router(DefaultApiRouter)
