# coding: utf-8
import logging
from logging.handlers import RotatingFileHandler
from opentelemetry import trace
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

from fastapi import FastAPI
from prometheus_fastapi_instrumentator import Instrumentator
from openapi_server.apis.default_api import router as DefaultApiRouter

# Импортируем метрики из отдельного файла (чтобы они зарегистрировались)
from metrics import *


file_handler = RotatingFileHandler(
    '/var/log/myapp/app.log',  
    maxBytes=10_000_000,      
    backupCount=1
)

logging.basicConfig(
    handlers=[file_handler],
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

app = FastAPI(
    title="Notebook API",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.0.1",
)

Instrumentator().instrument(app).expose(app)

resource = Resource.create({
    "service.name": "my-app",
    "service.version": "1.0.0"
})

provider = TracerProvider(resource=resource)

otlp_endpoint = "http://localhost:4343"
otlp_exporter = OTLPSpanExporter(
    endpoint=otlp_endpoint,
    insecure=True  
)

# console_exporter = ConsoleSpanExporter()
# provider.add_span_processor(SimpleSpanProcessor(console_exporter))

provider.add_span_processor(BatchSpanProcessor(otlp_exporter))



trace.set_tracer_provider(provider)

FastAPIInstrumentor.instrument_app(app)

app.include_router(DefaultApiRouter)
