galaxy_info:
  author: matthew
  description: Grafana server deployment role
  company: ansible
  role_name: grafana
  namespace: matthew1703

  license: BSD

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
