#SPDX-License-Identifier: MIT-0
---
- name: Restart prometheus service
  listen: Restart prometheus service
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: "{{ prometheus_service }}"
# handlers file for prometheus
