#SPDX-License-Identifier: MIT-0
---
- name: grafana / Download Grafana .deb package directly
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_10.2.2_amd64.deb
    dest: /tmp/grafana.deb
    mode: '0644'

- name: grafana / Install dependencies
  ansible.builtin.package:
    name:
      - adduser
      - libfontconfig1
      - musl
    state: present

- name: grafana / Install Grafana from local .deb
  ansible.builtin.apt:
    deb: /tmp/grafana.deb

- name: grafana / Start Grafana service
  ansible.builtin.systemd:
    name: "{{ grafana_service }}"
    state: started
    enabled: yes

- name: grafana / Copy grafana.ini
  ansible.builtin.copy:    
    src: "{{ monitoring_localconfig_path }}/files/grafana.ini"
    dest: "/etc/grafana/grafana.ini"
    mode: '0640'
    owner: grafana
    group: grafana
  notify: Restart grafana service

- name: "Add dashboards and datasources"
  import_tasks: dashboards_and_datasources.yml

# tasks file for grafana
