roles:
  - name: prometheus
    src: git@gitlab.com:roles7912543/prometheus.git
    version: main                 
    scm: git
  - name: grafana
    src: git@gitlab.com:roles7912543/grafana.git
    version: main                 
    scm: git
  - name: promtail
    src: git@gitlab.com:roles7912543/promtail.git
    version: main                 
    scm: git
  - name: loki
    src: git@gitlab.com:roles7912543/loki.git
    version: main                 
    scm: git
  - name: otl-collector
    src: git@gitlab.com:roles7912543/otl-collector.git
    version: main
    scm: git