#SPDX-License-Identifier: MIT-0
---
- name: Restart promtail service
  listen: Restart promtail service
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: "{{ promtail_service }}"
# handlers file for promtail
