#SPDX-License-Identifier: MIT-0
---
- name: Restart grafana service
  listen: Restart grafana service
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: "{{ grafana_service }}"
# handlers file for grafana
