all:
  hosts:
    159.194.203.159:
  children:
    monitoring:
      hosts:
        159.194.203.159:
      vars:
        ansible_user: root
        monitoring_localconfig_path: inventory/monitoring
        ansible_ssh_extra_args: '-o PubkeyAuthentication=no'
